name: "Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ruff Check
        uses: chartboost/ruff-action@v1

      - name: Ruff Format
        uses: chartboost/ruff-action@v1
        with:
          args: "format --check"
